services:
  caddy:
    image: nayukidayo/caddy:latest
    restart: unless-stopped
    logging:
      driver: local
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/Caddyfile
      - data:/data
      - config:/config

volumes:
  data:
  config:
